### ISSUE TITLE
Where is the latest version of this code?

### ISSUE THREAD

**Issue by hendisantika** [spring-cloud-samples/sample-zuul-filters#18]
Hi @spencergibb ,
Where is the latest version of this code?

Because I was using 2020.0.2 and add `implementation("org.springframework.cloud:spring-cloud-starter-netflix-zuul")`

But I can not import  ZuulFilter() to my code.

Any idea?

Thanks

**Comment by spencergibb** [comment]
Zuul is no longer part of spring cloud 2020.0.x
